### ISSUE TITLE
Link 'Learn More About Us' with a link

### ISSUE THREAD

**Issue by Ranjana-Kambhammettu** [NITK-KODE/nitk-kode.github.io#2]
Right now, when you click 'Learn More About Us', nothing happens. 

The change to make:
When 'Learn More About Us' is clicked, it should redirect to [NITK KODE](https://nitk-kode.github.io/NITK-KODE/ ) .

**Comment by AKASH-2106** [comment]
May I take up this issue?

**Comment by Ranjana-Kambhammettu** [comment]
> May I take up this issue?

Sure, go ahead!
