### ISSUE TITLE
Implement Contact Us in the website

### ISSUE THREAD

**Issue by Ranjana-Kambhammettu** [NITK-KODE/nitk-kode.github.io#4]
Right now, the 'Contact Us' does nothing. It needs to be implemented such that when someone sends a message, it should be sent to @priyansh32.

**Comment by greeshmaym** [comment]
Hey, I would like to work on this.May I take up ?

**Comment by priyansh32** [comment]
@greeshmaym Thank for your interest, currently this is open for only NITK students.

**Comment by famousfive1** [comment]
I would like to work on this. I thought maybe we can use pageclip (https://pageclip.co/) to forward the forms.
