### ISSUE TITLE
Fix Projects section of the website

### ISSUE THREAD

**Issue by Ranjana-Kambhammettu** [NITK-KODE/nitk-kode.github.io#5]
Customize the projects section to match the projects of this organization.

**Comment by greeshmaym** [comment]
Hey, I would like to work on it.May I take up the issue?

**Comment by farseenmanekhan1232** [comment]
Can you assign me the issue ??

**Comment by BenzeneAlcohol** [comment]
Hey, we are currently assigning issues only to NITK students., sorry.

**Comment by Ranjana-Kambhammettu** [comment]
I am self-assigning and completing this.
